# Generated by Django 5.1.5 on 2025-01-31 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('SupplierID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('SupplierName', models.CharField(max_length=200)),
                ('ContactDetails', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('ContractTerms', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('PurchaseOrderID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OrderDate', models.DateField(auto_now_add=True)),
                ('DeliveryDate', models.DateField(blank=True, null=True)),
                ('OrderStatus', models.CharField(max_length=200)),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.product')),
            ],
        ),
    ]
