# Generated by Django 5.1.5 on 2025-01-31 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HR', '0001_initial'),
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('SalesID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('PaymentMethod', models.CharField(max_length=200)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('SaleDate', models.DateField(auto_now_add=True)),
                ('EmployeeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='HR.staff')),
                ('ProductID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='Inventory.product')),
                ('StoreID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='Inventory.store')),
            ],
        ),
    ]
