# Generated by Django 5.1.5 on 2025-01-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartmentID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('DepartmentName', models.CharField(max_length=200)),
                ('Budget', models.IntegerField()),
            ],
        ),
    ]
