# Generated by Django 5.1.5 on 2025-01-31 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Finance', '0001_initial'),
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='ManagerID',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='HR.staff'),
        ),
    ]
