# Generated by Django 5.1.5 on 2025-01-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ProductName', models.CharField(max_length=200)),
                ('Category', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('StockLevel', models.IntegerField()),
                ('ReorderQuantity', models.IntegerField()),
                ('LastPurchaseDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductLocation',
            fields=[
                ('ProductLocationID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Quantity', models.IntegerField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('StoreId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('StoreName', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('ContactNumber', models.CharField(max_length=15)),
                ('TotalSales', models.IntegerField()),
                ('OperatingHours', models.IntegerField()),
            ],
        ),
    ]
