# Generated by Django 5.1.5 on 2025-01-31 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HR', '0001_initial'),
        ('Inventory', '0001_initial'),
        ('Procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SupplierID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Procurement.supplier'),
        ),
        migrations.AddField(
            model_name='productlocation',
            name='ProductID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocklocation', to='Inventory.product'),
        ),
        migrations.AddField(
            model_name='store',
            name='ManagerId',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR.staff'),
        ),
        migrations.AddField(
            model_name='productlocation',
            name='StoreId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocklocation', to='Inventory.store'),
        ),
    ]
