# Generated by Django 5.1.5 on 2025-01-31 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=200)),
                ('Role', models.CharField(max_length=200)),
                ('Salary', models.IntegerField()),
                ('StartDate', models.DateField(auto_now_add=True)),
                ('DepartmentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='Finance.department')),
            ],
        ),
    ]
